version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD= 
      - DB_NAME=proyectochat
    depends_on:
      - mysql
    networks:
      - chat-network
    command: sh -c "sleep 15 && npm start"  # Espera antes de levantar el backend

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - chat-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: proyectochat
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - chat-network

volumes:
  mysql_data:

networks:
  chat-network:
    driver: bridge
